chat_id: "-1002219262205"
bot_token: "7425383210:AAGwZl1RMRcLjbtBe7aZNYJGJJPkg-LKcBM"
routes:
  - path: "/hello"
    response: "Hello, World!"
    response_code: 200
  - path: "/goodbye"
    response: "Goodbye, World!"
    response_code: 200
  - path: "/reports/2024-05-21"
    response: "Internal Server Error"
    response_code: 500
    comment: "joinpdf.com has accessed this url"

